# This is a basic workflow to help you get started with Actions

name: web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'staticwebsite/**'

  # Allows you to run this workflow manually from the action tab
  workflow_dispatch:
    inputs:
      action_type:
        description: 'What action should be performed (apply/destroy)'
        required: true
        default: 'apply'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web"
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./staticwebsite
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: terraform init -upgrade
        working-directory: ${{ env.WORKING_DIR }}          

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }} 

      - name: 'Terraform apply'
        if: github.event.inputs.action_type == 'apply'
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform destroy'
        if: github.event.inputs.action_type == 'destroy'
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }} 
                    
      - name: 'Check last commit message'
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1)"
      - name: 'Conditionally run Terraform action'
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
        working-directory: ${{ env.WORKING_DIR }}
