# This is a basic workflow to help you get started with Actions

name: web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'staticwebsite/**'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web"
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./staticwebsite
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: terraform init -upgrade
        working-directory: ${{ env.WORKING_DIR }}          

      - name: 'Check last commit message'
        id: commit
        run: |
          MESSAGE=$(git log --format=%B -n 1)
          echo "Commit message: $MESSAGE"
          echo "::set-output name=message::$MESSAGE"
      
      - name: 'Conditionally run Terraform action'
        run: |
          echo "Commit Message: '${{ steps.commit.outputs.message }}'"
          if echo "${{ steps.commit.outputs.message }}" | grep -iq "destroy"; then
            echo "Running terraform destroy for all environments"
            for env in dev stage prod; do
              echo "Destroying environment: $env"
              terraform workspace select $env || continue
              terraform destroy -auto-approve
            done
          else
            echo "Running terraform apply"
            terraform apply -auto-approve
          fi
        working-directory: ${{ env.WORKING_DIR }}